name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Ändere das, falls ein anderer Branch genutzt wird

jobs:
  convert:
    runs-on: self-hosted  # Läuft direkt auf deinem Server
    container:
      image: quarto_quarto  # Dein lokales Docker-Image
      options: --rm  # Container nach Ausführung entfernen
    steps:
      - name: Checkout Repository
        #uses: actions/checkout@v4
        run: |
          git clone http://gitea:3000/linuxadmin/Labor.git          

      - name: Convert Markdown to PDF
        run: |
          mkdir -p output
          cd Labor
          quarto render --to pdf #--output-dir output
                    

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: output/*.pdf
