# Lokale Arbeit

TODO: CRLF / LF

## Geplante Inhalte

Das Ziel ist bei der lokalen Arbeit, dass du problemlos verschiedene Versionen 
von Dateien (zum Beispiel Unterrichtsvorbereitungen) auf deinem Rechner verwalten kannst, ohne bei den Dateinamen zu *kreativ* werden zu müssen. Gleichzeitig 
kannst du auf diese Weise auch einfach ein Backup deiner Daten erstellen -- allerdings
erst dann, wenn wir mit einem Server arbeiten^[Ein Backup auf dem gleichen Rechner ist nur sehr bedint sinnvoll!] 

Nachfolgend besprechen wir folgende Punkte

* Grundkonfiguration (einmalig)
* Erstellen eines Repositories
* Versionierung von Dateien
* Einfache Fehlerbehebung


Die hier angegebene Liste von \git-Befehlen ist keineswegs vollständig,
aber mit den markierten Befehlen sind fast alle Aspekte der 
täglichen Arbeit abgedeckt. Wir werden sie nachfolgend behandeln,
wenn auch nicht in genau dieser Reihenfolge.

| Befehl  | Befehl |
|---|---|
| \markcmd{git status} | `git clean`|
| \markcmd{git init}| \markcmd{git push}|
| \markcmd{git log}| \markcmd{git pull}|
| \markcmd{git add}| \markcmd{git diff}|
| \markcmd{git commit}| `git mergetool`|
| `git stash`| \markcmd{git show}|
| \markcmd{git checkout}| \markcmd{git fetch}|
| \markcmd{git merge}| \markcmd{git clone}|
| \markcmd{git branch}|\markcmd{git remote}|
| \markcmd{git switch}| |

Darüber hinaus gibt es noch fortgeschrittenere Befehle,
die meist der Fehlerbehebung dienen. Auf sie 
werden wir auch einen Blick werfen, aber nicht zu sehr 
in die Tiefe gehen.

| Befehl  | Befehl |
|---|---|
| `git reset` | `git revert`|
| `git cherry-pick`| `git restore`|
| `git rebase` ||


## Konfigurieren von git

Öffne die \gitbash. Auf Linux und MacOS öffnest du ein Terminal.
Zukünftig sreche ich pauschal von der \gitbash, meine aber immer auch das
Terminal der anderen Systeme!

Es ist aktuell egal, in welchem Ordner du dich befindest, wenn du 
die \gitbash öffnest, da es um globale Einstellungen geht. Sollte dir 
die Schrift im Fenster zu klein sein, kannst du sie mit \strg{+} vergrößern.

**Aktuelle Einstellungen ansehen**  
```bash
# Eingabe
git config --list
```

Was hier genau erscheint, hängt von deinem System ab. Du musst nun deinen 
Namen und deine Mailadresse an \git übergeben. Das spielt zwar erst im 
Team eine Rolle, wird aber als Voraussetzung gefordert!

**Einstellungen anpassen**  
```bash
# eigene Phantasiedaten verwenden
git config --global user.name "Susi Sandmann" 
git config --global user.email "susi@sandmann.de"
```

## Erstellen eines Repositories 
Die Voraussetzung für die Arbeit mit \git ist ein  *Projektordner*, 
in dem deine Projektdateien liegen sollen. 
In diesem Ordner wirst du dein erstes (lokales) Repository erstellen.   

### Ordner anlegen
Auch wenn das Erstellen eines Ordners 
mit den üblichen Werkzeugen des Betriebssystems natürlich 
möglich ist, werde ich mich dennoch konsequent auf die Arbeit 
im Terminal beschränken. 

```bash
cd       #<1> 
mkdir versuch_1  #<2>  
cd versuch_1    #<3>
```
1. Bei Windows landest du damit im Ordner \ordner{c:\\users\\<DEIN-NAME>}, 
   bei Linux und MacOS bist du in \ordner{/home/<DEIN-NAME}
2. Den Ordner erstellen (`mkdir = make directory = erstelle Ordner`)
3. Wechsle in den Ordner (`cd = change directory`)

Bist du dir unsicher mit dem Ort des Ordners:

```bash
pwd 
```

Da auch die \gitbash eine Form von abgespecktem Linux darstellt, 
gelten die nachfolgenden Befehle auf allen drei Systemen in gleicher Weise. 
Es ist sinnvoll, wenn du dir diese Liste bereit legst (oder die Befehle lernst).

**Wichtige Befehle**  

|Befehl|Kurzerklärung|
|------|-------------|
|`ls -la`| Auflisten aller Dateien im Ordner|
|`cd`|Wechsel in den Home-Ordner|
|`cd <ordner>`|Wechsel in *Ordner*|
|`cd ..`|Wechsel eine Ebene nach oben|
|`echo <Text>`|Ausgabe von Text|
|`> <datei>`|Ausgabe in Datei (s.u.)|
|`mkdir <ordner>`|Ordner erstellen|
|`rm -rf <ordner>`|Ordner ohne Rückfrage löschen|
|`cat <datei>`|Inhalt der Datei komplett ausgeben|
|`less <datei>`|Langsame Ausgabe, Ende mit `q`|


\samplestart
**TIPP**  
Im Terminal kannst du mit der *Pfeil hoch* Taste
durch die letzten Befehle blättern -- damit gehen 
manche Dinge sehr schnell!
\sampleend


### Anlegen des Repositories

Im Ordner \ordner{versuch\_1} gibst du nun folgenden Befehl 
ein^[Er ist in obiger Tabelle nicht markiert, weil man ihn 
nicht ständig braucht. Wichtig ist er aber trotzdem!]:

```bash
git init
```

Es erscheint eine Meldung, die je nach System etwas anders aussehen kann.
Die \gitbash macht leider nur englische Ausgaben! Hier musst du 
selbst übersetzen -- die deutschen Texte sind hier für das 
Verständnis besser.

```bash
Hinweis: Als Name für den initialen Branch wurde 'master' benutzt. 
Hinweis: Dieser Standard-Branchname kann sich ändern. Um den 
Hinweis: Namen des initialen Branches zu konfigurieren, der in 
Hinweis: allen neuen Repositories verwendet werden soll und
Hinweis: um diese Warnung zu unterdrücken, führen Sie aus:
Hinweis: 
Hinweis: 	git config --global init.defaultBranch <Name>
Hinweis: 
Hinweis: Häufig gewählte Namen statt 'master' sind 'main', 'trunk'
Hinweis:  und 'development'. Der gerade erstellte Branch kann
Hinweis:  mit diesem Befehl umbenannt werden:
Hinweis: 
Hinweis: 	git branch -m <Name>
Leeres Git-Repository in /tmp/versuch_1/.git/ initialisiert
```

Es hat sich eingebürgert^[Bedingt durch gesellschaftspolitische 
Strömungen, die *Master* mit Sklaverei gleichsetzen, aber eine 
Master-Arbeit hier nicht als Problem sehen.], den 
Arbeitszweig von *master* auf *main* umzubenennen:

```bash
git branch -m main 
```

Den Erfolg kannst du schnell überprüfen:

```bash
git status
```
Es sollte folgender Text (eventuell englisch) erscheinen:

```bash
Auf Branch main

Noch keine Commits

nichts zu committen (erstellen/kopieren Sie Dateien und benutzen
Sie "git add" zum Versionieren)
```

\samplestart 
**Hinweis**  
Wie im Hinweis oben steht, kannst du \git auch so konfigurieren, 
dass der Branch eines neu angelegten Repositories 
automatisch *main* genannt wird.

```bash 
git config --global init.defaultBranch main
```
\sampleend

## Einfacher Workflow
### Daten erstellen
Generell ist es (natürlich) möglich, jeden Typ von 
Datei mit \git zu versionieren. Eine der Stärken von 
\git ist allerdings der Vergleich von Versionsständen
auf Zeichenebene und deshalb sind Binärformate wie 
Musik, Bilder, aber auch Dokumente der gängigen Office-Produkte nur bedingt geeignet. 
Auch sehr große Dateien sind möglich -- aber nicht sinnvoll. Hier kann auf \git-LFS 
(Large File Storage) ausgewichen werden, was in diesem Workshop aber nicht Thema ist!

Nun erstellsst du eine erste Datei:

```bash
echo "Version 1" > datei1.txt
```

\samplestart
**Hinweis**  
Der Befehl `echo` erzeugt eigentlich eine Bildschirmausgabe,
die hier in eine Datei umgeleitet wird.
Das Symbol `>` überschreibt den Inhalt der Datei ohne Warnung, 
mit `>>` wird der Text an das Ende der Datei angehängt.
\sampleend

### Versionieren 

Einfaches Versionieren geht sehr schnell mit folgendem Befehl:

```bash
git add datei1.txt 
``` 

(Varianten dieses Befehls besprechen wir noch!)  

Nun schreibsst du einen Eintrag in die Projekt-Historie:

```bash
git commit -m "Erste Datei erstellt"
```

\samplestart
**Hinweis**  
Ein Commit ist ein Projektstand, an den du 
zurückkehren kannst, wenn etwas grob missglückt ist.
Vergeht zu viel Zeit (=viel Code) zwischen zwei 
Commits, so entstehen eventuell größere Verluste bei einem
Rücksprung zum alten Stand.  
Später im Workshop lernst du auch, wie du 
Commits nachträglich zusammenfassen kannst (=squash) 
um deine Entwicklungsschritte übersichtlich zu halten.
\sampleend 


Damit ist der Versionierungsablauf eigentlich schon definiert:

* Dateien, in denen du Änderungen vorgenommen hast, 
  sammelst du mit *add*
* Haben sich genug Daten angesammelt -- mit Sinnzusammenhang -- dann erstellst du einen *Commit* 
mit einer aussagekräftigen Beschreibung.

\samplestart
**Hinweise**  
Wenn du die Beschreibung lieber mit dem Editor machen möchtest, rufst du   
*nur* \cmd{git commit} auf (also ohne `-m`).  

In welchen Zeitabständen oder Sinnzusammenhängen du
Commits erstellst, ist alleine *deine* Entscheidung.
Du solltest aber bedenken, dass ein Rücksprung zu einem 
älteren Commit von *allen* Dateien die Vorgängerversion restauriert. Wenn du also zu viele 
Änderungen am Code vorgenommen hast, die behalten willst, dann wirst du einiges an Handarbeit haben. Deshalb lieber mehr Commits in kürzeren Abständen!
\sampleend

Ändere deine Datei nun ab, indem du eine Zeile ergänzt:

```bash
echo "Version 2" >> datei1.txt 
git add datei1.txt 
git commit -m "Erläuterung"
```

Die Historie besitzt nun zwei Punkte:

```bash
git log --oneline 

# Ausgabe
eaa6289 (HEAD -> main) Erläuterung
afbc9c5 Erste Datei erstellt
```

Die Hash-Werte (Zahlen am Zeilenanfang) können bei dir anders sein!

**Hinweis**  
Du kannst natürlich auch mehrere Dateien 
in einem Rutsch hinzufügen!

```bash
git add .  # Alle Dateien im aktuellen Ordner 
           # und den Unterordnern

git add --all  # (oder -A) fügt alle Dateien 
               # ab der obersten Ebene des 
               # Projekts hinzu  
```

Wir werden später sehen, was genau beim *add* 
passiert, zum Beispiel wenn man die gleiche Datei zwischen 
zwei Commits mehrfach ändert und *addet*.

Zusätzlich kann es natürlich auch sein, dass du 
bestimmte Dateien überhaupt nicht in die Versionsverwaltung
aufnehmen willst. Das ist zum Beispiel dann der Fall, wenn 
sich Kennwörter und Zugangsdaten in einer Datei befinden.
Sobald du die Namen dieser Datei(en) in eine Datei mit 
dem Namen `.gitignore` einträgst, werden sie beim *add* ignoriert.

```bash
# Format der Datei
*.log 
*.tmp 
zugangsdaten.txt
```

\samplestart
**Hinweis**  
\git versioniert keine leeren Ordner, weil es in 
ihnen keine Dateien gibt -- \git arbeitet dateibasiert! 
Soll ein leerer Ordner versioniert werden, so musst 
du eine Datei \datei{.gitkeep} im Ordner erstellen.  
Der Name ist eine Konvention, keine Verpflichtung.
Der führende Punkt *versteckt* die Datei bei den 
Standardeinstellungen im Explorer (o.ä.).
\sampleend