## Fehlerbehebung
Ein Versionsverwaltungsprogramm hat unter anderem 
die Aufgabe, ein Projekt in gewissem Umfang *revisionssicher*
zu protokollieren. Aus diesem Grund müssen bestimmte 
*Fehler* oder *dokumentierte Probleme* in der History 
erhalten bleiben, auch wenn sie später behoben wurden.

Allerdings treten auch bei der Verwendung von \git 
Fehler auf -- im Sinne von Bedienfehlern, zu frühem Committen, ...  
Derartige Fehler müssen möglichst auf dem eigenen Rechner repariert 
werden, bevor sie dem Team zur Verfügung gestellt werden. 
Nachfolgend besprechen wir einige Szenarien mit kleinen Beispielen. 
Aktuell ist das Arbeiten mit verschiedenen Entwicklungszweigen noch nicht 
Thema und auch Teamarbeit lassen wir außen vor. Wenn wir die aktuellen
Beispiele behandelt haben, ist der Schritt zur Teamarbeit nur sehr kurz.

\samplestart
**Ein Hinweis vorab**  
Im Netz findet man statt \cmd{restore} oft noch die Variante mit 
\cmd{checkout}, die früher üblich war.
\sampleend



### Kleiner Fehler 1 

Beim Programmieren entsteht ein Fehler, bei dem eine manuelle Behebung zu 
aufwändig ist. Die einfachere Lösung ist die Wiederherstellung der betroffenen 
Datei in der letzten lauffähigen Version. Solange kein *add* erfolgt ist, kannst 
du die Datei aus dem Stage wieder in das \work kopieren (siehe Hinweis unter dem Code!). 

```bash
git init beispiel_1
cd beispiel_1
git branch -m main

# alles funktioniert
echo "Alles gut" > datei.txt
git add .
git commit -m "alles gut"

# Hier kommt der Fehler
echo "Mist gebaut" >> datei.txt

###### Alte Version vom Stage wieder herstellen
git restore datei.txt  
```

\samplestart
**Hinweis**  
Vorher habe ich geschrieben, dass bei einem Commit die Dateien
aus dem Stage in die Projekthistorie übertragen und aus 
dem Stage entfernt werden. Intern funktioniert das allerdings 
etwas anders. Die Datei *index* enthält die Namen und Hashes des 
aktuellen Commits (tree). Mit einem *add* werden Dateinamen ergänzt.
Beim Commit wird die Datei nicht geleert, die Hashes bleiben also verfügbar.
Dass `git status` diese Dateien nicht mehr anzeigt, liegt einfach daran, dass 
der Befehl eigentlich nur ein *diff* zwischen *index* und aktuellem *tree* 
ausführt. 
\sampleend

### Kleiner Fehler 2

Der Fehler wurde bereits ge-add-et. Damit gibt es im 
Stage keine Version zum Rückkopieren. Du musst also einen 
weiteren Schritt rückwärts gehen.

```bash
########### IRRWEG !!!!!!!!! #########
git init beispiel_2
cd beispiel_2
git branch -m main

# alles funktioniert
echo "Alles gut" > datei.txt
git add .
git commit -m "alles gut"

# Hier kommt der Fehler
echo "Mist gebaut" >> datei.txt
git add .   # DAS ist anders!

#####################
###### Das geht jetzt nicht, weil der 
###### Stage die falsche Version enthält.
#####################
git restore datei.txt  
```

Du musst mit \cmd{git log} den Hash vom letzten 
Commit ermitteln und dann geht

```bash
git restore --source=<HASH> datei.txt 
```

Falls du die Datei schon längere Zeit bearbeitet hast und die 
Änderungen immer mit \cmd{add} auf den Stage geschrieben 
hast, wirst du natürlich Verluste haben! Hättest du kleinschrittig
committet, so wären die Verluste geringer.

\samplestart
**Zusatz**  
Mit \cmd{restore} können natürlich nicht nur Dateien aus dem direkt 
vorausgehenden Commit entnommen werden! Kennst du den Hash, so kannst 
du auf jeden Commit zugreifen.
\sampleend

### Größerer Fehler 1

Du hast nach dem letztem Commit viele Fehler in einer Vilezahl 
von Dateien erzeugt und willst deshalb den aktuellen Stand verwerfen. 
Hier hilft \cmd{reset}. Diesen Befehl gibt es in 3 Versionen

* hard
* mixed
* soft

#### Hard
```bash
git init beispiel_3
cd beispiel_3
git branch -m main

# alles funktioniert
echo "Alles gut datei1" > datei1.txt
echo "Alles gut datei2" > datei2.txt
# ... viele Dateien
git add .
git commit -m "alles gut"

# Hier kommen DIE Fehler
echo "Mist gebaut" >> datei1.txt
echo "Mist gebaut" >> datei2.txt
# ... viele Fehler in vielen Dateien

# Rücksetzen des kompletten Projekts auf den letzten Commit 
git reset --hard HEAD 
```

Hiermit ist alles gelöscht, was du nach diesem Commit 
produziert hast -- unwiederruflich weg!

\samplestart
**Hinweis**  
Du kannst in der Commit-History auch weiter zurück springen
und somit die letzten Commits verwerfen. Das ist völlig problemlos,
solange du alleine, lokal auf deinem Rechner arbeitest. Im Team
oder auch nur mit Serverabgleich wird das extrem problematisch!
\sampleend

#### Mixed
Das ist so ziemlich die gebräuchlichste Variante.

```bash
git reset --mixed <HASH>
git reset <HASH>
```

Die Commits werden gelöscht, alle Änderungen liegen aber immer 
noch in den Dateien des \work vor. Du kannst also Korrekturen 
vornehmen und danach neue Commits erstellen. 
Auch hier ist natürlich wichtig, dass die Commits deinen Rechner
vorher noch nicht verlassen hatten!

**Demo**  

```bash
rm -rf demo_mix 
git init demo_mix
cd demo_mix
git branch -m main 


for i in {1..10}; do 
  echo "Zeile $i" >> datei.txt 
  git add . && git commit -m "Zeile $i eingefügt"
  git tag commit_$i
done 

cat datei.txt # liefert 10 Zeilen 

git reset --mixed commit_4

cat datei.txt # liefert immer noch 10 Zeilen

git log --oneline # liefert 4 Zeilen

git status # zeigt eine geänderte, versionierte Datei 
```

#### Soft

Wenn du in obigem Script das \cmd{--mixed} durch \cmd{--soft}
ersetzt, dann passiert auf den ersten Blick nichts anderes als bei \cmd{--mixed}. Beim \cmd{status} erscheint die Datei mit den 10 Zeile 
aber nun bereits im Stage und könnte sofort commitet werden.


### Da war doch mal was
Manchmal -- gerade bei Dokumentationen oder anderen Texten -- hätte man gerne 
die Version zurück, die man vor einigen Tagen gelöscht hat. Bei \git hast du 
Zugriff auf alle alten Versionen! Allerdings ist oft die Frage, in welchem Commit 
sich die Version versteckt. Hier wird es nötig, sich rückwärts durch die ensprechenden
Commits zu arbeiten. Dabei gibt es allerdings eine Besonderheit, die du kennen musst.
Nachfolgendes Script erzeugt das passende Szenario:


```bash
git init suche
cd suche
git branch -m main

for i in {1..5};do 
 echo "Version $i" > datei.txt 
 git add .
 git commit -m "Version $i"
done 

echo "gewünschte Version" > datei.txt 
git add .
git commit -m "Version 6"

for i in {7..10};do 
 echo "Version $i" > datei.txt 
 git add .
 git commit -m "Version $i"
done 
```

Du weißt aus dem Script, dass Version 6 die Datei in der gewünschten Form enthält.
Im Ernstfall weißt du das wahrscheinlich nicht. Du beginnst also mit der Suche:

```bash
git log --oneline

# Ausgabe
b55b329 (HEAD -> main) Version 10
0149855 Version 9
a4bc57f Version 8
95a37c9 Version 7
d370ffb Version 6
25fd886 Version 5
c745eda Version 4
4a64eef Version 3
68a4d14 Version 2
461eee6 Version 1
```

Am Besten kopierst du dir die Ausgabe in eine Datei, damit du immer Zugriff auf die Hashwerte 
der Commits hast. Nimm nun als Beispiel einen Sprung zu Version 7.

```bash
git checkout 95a37c9
```

Nun kommt eine große Warnung, die dich darüber informiert, dass du gerade 
außen an der Versionsverwaltung entlang krabbelst. Da du noch nicht mit 
Branches arbeitest, solltest du aktuell keinerlei 
Änderungen an den Dateien vornehmen! In die Dateien hinein sehen ist keine
Änderung -- das ist also ok. Du kannst auch Teile der Inhalte wegkopieren 
(in einen anderen ordner) um sie später weiterverwenden zu können.

```bash
Hinweis: Wechsle zu '95a3'.

Sie befinden sich im Zustand eines 'losgelösten HEAD'. 
Sie können sich umschauen, experimentelle Änderungen 
vornehmen und diese committen, und Sie können alle möglichen 
Commits, die Sie in diesem Zustand machen, ohne Auswirkungen 
auf irgendeinen Branch verwerfen, indem Sie zu einem
anderen Branch wechseln.

Wenn Sie einen neuen Branch erstellen möchten, um Ihre erstellten 
Commits zu behalten, können Sie das (jetzt oder später) durch 
Nutzung von 'switch' mit der Option -c tun. Beispiel:

  git switch -c <neuer-Branchname>

Oder um diese Operation rückgängig zu machen:
  git switch -

Sie können diesen Hinweis ausschalten, indem Sie die 
Konfigurationsvariable 'advice.detachedHead' auf 'false' setzen.

HEAD ist jetzt bei 95a37c9 Version 7
```

Hast du die relevanten Zeilen kopiert, so kannst du mit folgendem
Befehl wieder in die Versionsverwaltung einsteigen:

```bash
git checkout main 
```

Die Fehlerbehebung kann auch das Löschen ganzer 
Entwicklungs- oder Testzweige (Branches) bedeuten,
was wir später noch besprechen.

\samplestart
**Trick**  
Manchmal soll auch nur die Version gelöscht werden,
  die irrtümlich auf den Stage geschoben wurde. Dabei darf das 
  \work nicht verändert werden. Das erreichst du mit
   `git restore <dateiname> --staged`.  
  Das braucht man eigentlich nur, wenn diese Datei doch nicht im 
  nächsten Commit enthalten sein soll.
\sampleend

### Was ist mit Revert?

Ja -- \cmd{revert} gibt es und es spielt bei der Arbeit im 
Team auch eine große Rolle. Bei der lokalen Arbeit wirst 
du diesen Befehl sehr selten brauchen -- \cmd{reset}
und \cmd{checkout} sind hier meist einfacher und schneller.
Du wirst im Abschnitt über die Teamarbeit aber noch mehr 
darüber hören! 

In der Theorie liest \git die Änderungen, die ein 
Commit vorgenommen hat, invertiert diese Änderungen 
und wendet sie auf den aktuellen Stand an. Dabei wird 
ein neuer Commit erstellt. Im Kern handelt es sich um 
eine Art von Merge. Wenn es sich bei dem aufzuhebenden
Commit nicht um den HEAD handelt, sind Konflikte im 
Normalfall fast nicht zu vermeiden! 

**Typischer Ablauf**  

```bash

git log --oneline 

# Ausgabe 
4353add (HEAD -> master) C: Modify B-line
f9d333a B: Add B-line
0d43a86 A: Add A-line
3954336 Initial 

git revert 0d43a86

# Ausgabe 
KONFLIKT (ändern/löschen): file.txt gelöscht in (empty tree) und 
geändert in HEAD. Stand HEAD von file.txt wurde im Arbeitsbereich gelassen.

error: Konnte "revert" nicht auf 0d43a86... (A: Add A-line) ausführen

Hinweis: Lösen Sie alle Konflikte manuell auf, markieren Sie diese mit
Hinweis: "git add/rm <Pfadspezifikation>" und führen Sie dann
Hinweis: "git revert --continue" aus.
Hinweis: Sie können stattdessen auch diesen Commit auslassen, indem
Hinweis: Sie "git revert --skip" ausführen.
Hinweis: Um abzubrechen und zurück zum Zustand vor "git revert" zu gelangen,
Hinweis: führen Sie "git revert --abort" aus.
```

Die Anleitung für das weitere Vorgehen steht komplett in den Hinweisen:

* Datei öffnen und Konflikt bereinigen
* \cmd{git add .}
* \cmd{git revert --continue}






xxxxxxxxxxxxxxxxxxxxxxxxxx AUSGLIEDERN xxxxxxxxxxxxxxxxxxxxxxxxx

Zum Verständis der Problematik dennoch ein Beispiel.
Angenommen, du erstellst ein Programm zur Berechnung 
des Body-Mass-Index und gehst extrem kleinschrittig 
mit den Commits um. Dein Ablauf wäre dann - jeder Punkt 
ist ein Commit (siehe Nummer):

* (1) Java-Boilerplate
* (2) Ausgabefunktion ohne Übergabeparameter und Blankotext
* (3) Eingabefunktion für die Körpergröße
* (4) Ändern der Ausgabefunktion für Übergabe von String  
  Das ist der Fehler, weil du später *double* willst
* (4) Eingabefunktion für die Körpermasse
* (5) Berechnungsfunktion

Nun verdrahtest du das alles in der *main*-Funktion
und stellst fest, dass der Übergabeparameter den 
falschen Typ besitzt.  
Aus desem Grund möchtest du diesen Commit -- der ja NUR diese 
Funktion betrifft -- rückgängig machen.

In meinem System lauten die Hashes wie folgt:

```bash
git log --oneline

# Ausgabe
a93cb87 (HEAD -> main) kombi
e676f14 berechnung
d497b2f eingabe 2
4fe5b44 ERROR
2c9c7f1 eingabe 1
d051611 ausgabe
9201570 initial
```

Der Befehl *revert* verläuft nun wie folgt:

```bash
git revert 4fe5 # 4 reichen

# Ausgabe
automatischer Merge von Main.java
KONFLIKT (Inhalt): Merge-Konflikt in Main.java
error: Konnte "revert" nicht auf 4fe5b44... (ERROR) ausführen
Hinweis: Lösen Sie alle Konflikte manuell auf, 
Hinweis: markieren Sie diese mit
Hinweis: "git add/rm <Pfadspezifikation>" und führen Sie 
Hinweis: dann "git revert --continue" aus.
Hinweis: Sie können stattdessen auch diesen Commit 
Hinweis: auslassen, indem Sie 
Hinweise: "git revert --skip" ausführen.
Hinweis: Um abzubrechen und zurück zum Zustand 
Hinweise: vor "git revert" zu gelangen,
Hinweis: führen Sie "git revert --abort" aus.
```

Es gibt also einen *Konflikt*. Der Inhalt der Datei sieht 
aktuell so aus:

```bash
cat Main.java 

# Ausgabe 
import java.util.Scanner;

public class Main{
  public static void main(){

    int cm = eingabeCM();
    int kg = eingabeKG();
    double bmi = berechnung(cm, kg);
    ausgabe(bmi);
  }

  public static void ausgabe(){
    System.out.print("Dein BMI beträgt: ");
    System.out.println(42);
  }

  public static int eingabeCM(){
    System.out.print("CM:");
    int cm = new Scanner(System.in).nextInt();
   return cm;
  }

<<<<<<< HEAD
  public static int eingabeKG(){ //Größe in cm
        System.out.print("KG:");
        int kg = new Scanner(System.in).nextInt();
        return kg;
    }

  public static double berechnen(int cm, int kg){
        double bmi = kg / Math.pow(cm /100.0, 2);
        return bmi;
    }

=======
>>>>>>> parent of 4fe5b44 (ERROR)
}
```

Wie du erkennen kannst, wurde die *relevante Funktion* korrekt 
zurückgesetzt. Der Konflikt tritt erst weiter unten in der 
Datei auf.  

Warum passiert das?  

