# Arbeiten im Team
## Herausforderungen
Das Arbeiten im Team stellt dich vor zwei Probleme:

* Welche Server-Infrastruktur sollst du verwenden?
* Was ändert sich am Workflow in \git 

Beide Punkte sollen nachfolgend besprochen werden, 
wobei es zwangsläufig Überschneidungen geben wird.

### Infrastruktur
Im Kern ist es egal ob wir vom Setup im Klassenzimmer
oder im Internet sprechen -- sobald ein Netzwerk beteiligt ist, 
sind höchstens Sicherheitsaspekte ein Thema, die Basistechnik 
bleibt gleich.

Für eine server-basierende Teamarbeit gibt es folgende Varianten

* einfacher \git-Server  
  Die Installation ist einfach, die Grundkonfiguration auch.
  Der Zugriff erfolgt über ssh. Soll das ohne Kennwort 
  funktionieren, so müssen Schlüssel erzeugt und auf den Server 
  eingepflegt werden. Später führt um die Schlüssel aber 
  ohnehin kein Weg herum.

* \git-Server mit kennwortlosem Zugriff über http.  
  Funktioniert, ist aber keinesfalls für den Live-Einsatz 
  über einen längeren Zeitraum im Internet zu empfehlen.
  Die entsprechenden Docker-Files befinden sich in den 
  Materialien.
  (Basis: [ynohat](https://github.com/ynohat/git-http-backend) )

* Ein \git-Server mit *Gitea*  
  Gui-basiertes System mit vielen Optionen und weniger komplex als 
  *GitLab* 

* Ein \git-Server mit *GitLab* 

Bei allen Varianten ist im Prinzip eine direkte Installation 
auf den Server (nicht empfohlen) oder der Einsatz von Docker
(sinnvoll) möglich. Die Anleitungen für die einzelnen Varianten 
befinden sich weiter hinten im Script.

### Änderungen am Workflow
Bei der Arbeit im Team ändert sich im Vergleich zum 
lokalen Arbeiten zunächst wenig. Die
Schritte *branch, add, commit, ...* 
funktionieren wie auch bisher. Neu sind 
allerdings die folgenden Schritte

* Initiales Holen des Repos auf den eigenen Rechner (=clone)
* Regelmäßiges Abrufen des aktuellen Standes (=pull)
* Veröffentlichen des eigenen Standes (push)

Hierbei sind einige Spielregeln zu beachten, damit es nicht
zu Problemen kommt. Diese Regeln werden meist als Workflow
oder im Speziellen auch als GitFlow bezeichnet. Es gibt hier 
zwar gewisse -- aber keinesfalls verbindliche -- Standards.
Jede Firma stellt für \git ihre eigenen, fest vorgeschriebenenen
Abläufe auf, an die sich die Mitarbeiter zu halten haben.

### Mögliche Vereinbarungen
Auch die folgenden Vereinbarungen müssen nicht in jeder Firma 
oder jedem Projekt umgesetzt werden!

**Verantwortung**  
Im Projekt gibt es einen \branch{main}, der aber durch 
entsprechende Maßnahmen für *einfache* Mitarbeiter 
schreibgeschützt ist. Änderungen dürfen nur nach 
gründlichen Tests und Code-Reviews in diesen Zweig 
aufgenommen werden. In der Regel gilt hier auch ein 
*Mehr-Augen-Prinzip* oder noch weiter gestaffelte 
Zuständigkeitshierarchien.  

**Arbeitsbranch**  
Je nach Größe des Projekt-Teams gibt es einen oder mehrere
\branch{development}-Branches. Die Mitarbeiter holen sich 
diesen Zweig und lassen von ihm ihre eigenen Arbeitszweige
(Feature-Branches, Bugfix-Branches) ausgehen. Ist ihre 
Arbeit dort beendet, muss der Code getestet werden und dann 
erst erfolgt der Merge in den \branch{development}-Branch.

#### Etwas mehr Details
Da im Team mehrere Personen zu unvorhersehbaren Zeitpunkten 
Änderungen am Code vornehmen, muss jeder
Mitarbeiter dafür sorgen, dass er immer die aktuellste Version 
vorliegen hat. Da er seine Entwicklung aber in seinem 
eigenen \branch{Feature}-Branch vorantreibt, müssen 
diese Änderungen der Kollegen dort aber erst ankommen -- dies geschieht
durch Merges in die andere Richtung -- also Merges **in** den eigenen
Branch.

**Beispiel**  

Aus Platzgründen zeichne ich das Branch-Diagramm hier
waagrecht. Man sieht, dass beim Commit $m_2$  der 
\branch{devlopment}-Branch abzweigt und dann vom Commit $d_1$ 
sofort der \branch{feature}-Branch.  
Ab jetzt werden regelmäßig Änderungen am \branch{development}-Branch
auf den eigenen \branch{feature}-Branch gezogen, um so immer 
den aktuellen Stand zu haben.

{{< include bilder/tikz/workflow1.tikz >}}

Merges in die Andere Richtung -- also vom \branch{feature}- auf
den \branch{development}-Branch sieht man noch keine. Auch der
\branch{main}-Branch wurde noch nie aktualisiert.

#### Pull und fetch

Die Grundidee von *holen* und *veröffentlichen* ist 
relativ einfach und eventuell muss man den Schülern 
auch nicht mehr erzählen. Da aber Code von anderen 
Entwicklern auf deinen Rechner kommt, solltest du 
diesen eventuell nicht ungesehen in deine Entwicklung
aufnehmen. Der Befehl \cmd{git pull} macht aber genau das.  
Willst du an dieser Stelle sicher gehen, so machst
du zuerst \cmd{git fetch} und siehst dir die Änderungen 
an -- siehe weiter unten. Im Anschluss kannst du
sie dann mit \cmd{git merge} übernehmen.

## Hands on
In dieser Praxiseinheit sollst du die Arbeit im Team
auf deinem eigenen Rechner simulieren. Dafür brauchst du:

* Ein *Server*-Repository
* Ein Repository für einen Benutzer Max
* Ein Repository für eine Benutzerin Susi

Bevor wir diesen Setup umsetzen, müssen wir kurz den 
Begripp *origin* klären, der uns nun öfter begegnet!
Für die einzelnen Schritte gibt es Scripts in den Kursmaterialien!

### origin 
**Origin.sh**  
```{.bash include="src/hands_on_III/origin.sh"}
```
Das Script \script{origin.sh} erstellt dir

* Ein Repository mit dem Namen *entfernt*, das einen Server darstellt
* Ein Repository mit dem Namen *lokal*, das deinen Rechner darstellt, 
  indem es eine Kopie von *entfernt* erstellt (=clone).

Öffne eine \git-Bash in einem Spielordner und führe das 
Script \script{origin.sh} aus. Die Ausgabe wird bei dir minimal 
abweichen.

```bash
Leeres Git-Repository in /tmp/labor1/entfernt.git/ initialisiert
Klone nach 'lokal' …
warning: Sie scheinen ein leeres Repository geklont zu haben.
Fertig.
Auf Branch main

Noch keine Commits

nichts zu committen (erstellen/kopieren Sie Dateien und benutzen
Sie "git add" zum Versionieren)
```

Durch 

```bash 
git remote -v 
```

siehst du, woher das Repository stammt. Bei dir ist natürlich
ein anderer Pfad zu sehen!

```bash
origin	/tmp/labor1/entfernt.git (fetch)
origin	/tmp/labor1/entfernt.git (push)
```

Wenn also in den folgenden Ausgaben und Befehlen *origin* 
erscheint, dann ist **dieser** Pfad gemeint. *Pfad* kann allerdings
auch eine Netzwerkverbindung zu einem Server sein -- das ist 
sogar der Normalfall.

Mit \branch{origin/main} ist immer der Branch im entfernten Repository (z.B. Server)
gemeint, \branch{main} (ohne *origin*) bezieht sich auf den Branch in deiner lokalen Kopie.


### Eigentliches Labor
Der nachfolgende Setup erstellt 

* einen Ordner
* im Ordner ein vollwertiges Repository (--bare)
* eine lokale Kopie des Repositories mit dem Namen *susi*
* eine lokale Kopie des Repositories mit dem Namen *max*

Öffen in einem geeigneten Ordner eine \git-Bash und 
führe das Script \script{susi\_und\_max.sh} aus.

Beachte, dass in dem Script im oberen Teil etwas Overhead
nötig ist, damit Susi und Max nicht einfach nur ein leeres Repository clonen,
sondern die realistischere Situation mit zumindest einer Datei vorfinden:

```{.bash include="src/hands_on_III/susi_und_max.sh"}
```

Öffne ein zweites Fenster im gleichen Ordner und entscheide 
dich, welches für *Susi* und welches für *Max* stehen soll.
Wechsle jeweils in das Repository (\cmd{cd susi} und \cmd{cd max}).

Wir betrachten nun das Repository von Susi und lassen uns den Status ausgeben:

```bash
git status
```

Es sollte erscheinen

```bash
Auf Branch main    <<< das ist der von Susi
Ihr Branch ist auf demselben Stand wie 'origin/main'. <<< Server

nichts zu committen, Arbeitsverzeichnis unverändert
```

Im Prinzip hat Susi also eine identische Kopie des 
Repositories erstellt. Der \branch{main}-Branch 
gehört *Susi* in *diesem* Repository.
Die Statusmeldung sagt dir, dass beide Branches, *main* (Susis)
und *origin/main* (der im Original Repo) auf dem gleichen Stand sind..  

Nachfolgend stehen die Bezeichnungen *SERVER* und *SUSI* für die 
entsprechenden Repositories (bei MAX ist das analog).

Susi erstellt in *SUSI* eine Datei und einen Commit:

```bash
echo "Hallo Welt" >> datei.txt 
git add datei.txt 
git commit -m "Begrüßung"
```

und betrachtet den Status erneut:

```bash
Auf Branch main
Ihr Branch ist 1 Commit vor 'origin/main'.
  (benutzen Sie "git push", um lokale Commits zu publizieren)

nichts zu committen, Arbeitsverzeichnis unverändert
```

Der \git-Ordner führt also Buch über die Beziehung zwischen 
den Repositories und sagt ihr, dass *SUSI* einen 
Commit weiter vorne ist, als *SERVER*.  
Das macht \git, indem es *Pointer* auf Commits
setzt (also quasi eine Datei im \ordner{.git}-Ordner führt, 
wo der aktuelle Hash enthalten ist.)

```bash
...
├── config
├── description
├── HEAD           #<1>
├── hooks
│   ├── applypatch-msg.sample
...
├── packed-refs #<3>
└── refs
    ├── heads
    │   └── main
    ├── remotes
    │   └── origin
    │       └── HEAD  #<2>
    └── tags
```
1. Enthält den Hash vom letzten Commit in SUSI
2. Enthält den Hash vom letzten Commit von SERVER
3. Siehe nachfolgender Text

Ein \cmd{git log --oneline} zeigt dir:

```bash
78db34e (HEAD -> main) Begrüßung         <<<< SUSI
d46681d (origin/main, origin/HEAD) Init  <<<< SERVER 
```

Und ein Blick in die beiden Dateien liefert die Hashes --
zumindest fast, denn \git hat hier schon wieder optimiert
und den Hash vom *origin/master* in die Datei *packed-refs* 
umgelagert. 

Der *SERVER* weiß vom SUSI Commit noch nichts -- die Repositories 
haben ja auch noch nicht miteinander kommuniziert! Wenn Max in seinem
Repository *MAX* nachsieht kann er Susis Datei nicht sehen und 
daran würde auch ein \cmd{git pull} nichts ändern.

Susi führt nun einen Push aus:

```bash
git push origin main 
```
*Git* kommentiert das:

```bash
Objekte aufzählen: 4, fertig.
Zähle Objekte: 100% (4/4), fertig.
Delta-Kompression verwendet bis zu 6 Threads.
Komprimiere Objekte: 100% (2/2), fertig.
Schreibe Objekte: 100% (3/3), 292 Bytes | 292.00 KiB/s, fertig.
Gesamt 3 (Delta 0), Wiederverwendet 0 (Delta 0), 
Pack wiederverwendet 0
To /tmp/labor2/entfernt
   d46681d..78db34e  main -> main
``` 

und jetzt liefert der Status:

```bash
Auf Branch main                                        <<<< SUSI
Ihr Branch ist auf demselben Stand wie 'origin/main'.  <<<< SERVER 

nichts zu committen, Arbeitsverzeichnis unverändert
```

Die Zeiger in \ordner{.git} wurden also auf den gleichen Hash gesetzt.

**Wechseln wir zu Max**  

Max hat noch sein ursprüngliches Repository und möchte auf 
Änderungen am Server prüfen.

```bash
git fetch   # pull würde gleich auch mergen
```

Als Ausgabe bekommt er
```bash
remote: Objekte aufzählen: 4, fertig.
remote: Zähle Objekte: 100% (4/4), fertig.
remote: Komprimiere Objekte: 100% (2/2), fertig.
remote: Gesamt 3 (Delta 0), Wiederverwendet 0 (Delta 0), 
Pack wiederverwendet 0
Entpacke Objekte: 100% (3/3), 272 Bytes | 272.00 KiB/s, fertig.
Von /tmp/labor2/entfernt
   d46681d..78db34e  main       -> origin/main
```

Sein Status sagt ihm

```bash
Auf Branch main     <<<< MAX
Ihr Branch ist 1 Commit hinter 'origin/main', und kann vorgespult 
werden.
(benutzen Sie "git pull", um Ihren lokalen Branch zu aktualisieren)

nichts zu committen, Arbeitsverzeichnis unverändert
```

Mit *vorspulen* ist ein Merge gemeint. Max will aber zuerst wissen,
*was* sich geändert hat.

```bash
git log origin/main
```

Max sieht den Commit, der noch nicht in seinen Branch integriert ist.

```bash
commit 78db34e31.....27eac06aa4dda5c50cdb (origin/main, origin/HEAD)
Author: susi <susi@t-online.de>
Date:   Wed Jan 29 12:39:38 2025 +0100

    Begrüßung

commit d46681db23c9e2b3f5379a951c026e3d673fe3e0 (HEAD -> main)
Author: wolfgang <lehrer@t-online.de>
Date:   Wed Jan 29 12:34:48 2025 +0100

    Init
```

Schön sieht man den Hash auch mit 

```bash
git show-ref
```

Der lokale \branch{main} befindet sich noch bei d46681, der 
entfernte \branch{origin main} hingegen bei 78db34.  
Durch folgenden Befehl sieht Max die Differenz der Versionen:

```bash
git show 78db34
```

Dabei wird auch der Dateiname angezeigt und wenn dir die Diff-Darstellung zu 
verwirrend ist, kannst du auch einfach den Inhalt der Datei anzeigen lassen:

```bash
git show 78db34e3:datei.txt
```

Max erkennt, dass es problemlose Änderungen sind und übernimmt
sie in seinen Branch:

```bash
git merge
```
Die Hashes zeigen, was passiert:

```bash
Aktualisiere d46681d..78db34e
Fast-forward
 datei.txt | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 datei.txt
```

Hätte Max größeres Vertrauen, so würde er sich diese Recherche 
sparen und einfach ein \cmd{git pull} ausführen. Im Prinzip ist
dieser Befehl die direkte Nacheinanderausführung von \cmd{fetch} 
und \cmd{merge}.


### Einige Fragen

**Wie starte ich from Scratch**  

Wie man vorgehen muss, hängt sehr stark von deiner 
Umgebung ab. Da es hier einige Varianten gibt, habe 
ich das in den Anhang ausgelagert!


```bash
# auf dem Server 
git init --bare musterrepo
cd musterrepo
git branch -m main 
```

```bash
# auf dem Client
# Besondere Schritte NUR auf dem ersten Client nötig
git clone gituser@server:port/pfad/zu/repo.git 
git switch -c main 
echo "Welcome" > Readme.txt 
git add Readme.txt 
git commit -m "initial"
git push -u origin main 
```

Jeder weitere Benutzer clont nun ein funktionsfähiges Repostory.

**Muss ich das 'origin main' immer angeben?**  

Auch wenn der Branch \branch{main} besonders klingt, 
ist er doch ein ganz normaler Branch. Seine Besonderheit  
ist lediglich, dass er durch das Clonen auch gleichzeitig 
als *upstream-branch* definiert wurde -- deshalb funktioniert
statt \cmd{git pull origin main} auch die kurze Version \cmd{git pull}
(analog für \cmd{git push}).

Wenn du einen neuen Branch anlegst und einen commit 
pushen willst:

```bash
git switch -c probe 
echo "test" > probedatei.txt 
git add probedate.txt 
git commit -m "Datei ergänzt"
git push 
```

dann gibt es eine Fehlermeldung

```bash
Schwerwiegend: 
Der aktuelle Branch probe hat keinen Upstream-Branch.
Um den aktuellen Branch zu versenden und den Remote-Branch
als Upstream-Branch zu setzen, benutzen Sie

    git push --set-upstream origin probe

Damit das automatisch für Branches ohne Upstream-Tracking passiert,
siehe 'push.autoSetupRemote' in 'git help config'.
```

Willst du den Branch pushen, dann musst du obigen Befehl verwenden
oder kürzer

```bash
git push -u origin probe 
```

Theoretisch geht es auch, von einem *nicht upstream* Branch 
direkt auf einen Upstreambranch zu pushen -- das läuft aber 
am lokalen Branch vorbei, dem dann ein Commit fehlt:

```bash
git push origin probe:main 
```

\samplestart
**Hinweis**  
Du hast nun mehrfach *origin main* aber auch *origin/main* 
gesehen. Was ist der Unterschied? Die erste Variante meint 
wirklich den Branch *main* auf dem Server, der sich hinter *origin*
verbirgt.  
Die zweite Variante ist eher wie eine Pfadangabe innerhalb von \Git 
auf dem lokalen Rechner zu verstehen.
\sampleend


**Ist es egal, in welchem Branch ich fetch/pull/push ausführe?**  
Jein.  
Beim Pushen kann nicht viel schief gehen. Upstream-Branches laufen 
automatisch und wenn sie nicht als upstream konfiguriert sind, 
dann geht der Push (standardmäßig) nicht.  

Beim Pull sieht es anders aus. Du kannst jeden Remote-Branch 
in jeden lokalen Branch *pullen* -- also *mergen*. Ist 
der aktuelle Branch als Upstream konfiguriert, holt sich ein
kurzes \cmd{git pull} die richtigen Daten. Ein \cmd{git pull <branch>} 
holt aber genau das, was du angegeben hast! Das ist eine 
Fehlerquelle!
