## Actions

Dieses Thema ist nun so groß und speziell, dass wir hier an unsere
Genzen stoßen. Ich möchte nur kurz das Vorgehen für unser Szenario 
der Bucherstellung besprechen. Leider ist der Setup zum Zeitpunkt 
des Schreibens nicht wirklich geradlinig. Vielleicht geht das mittlerweile 
allerdings auch einfacher. Mein Problem war die fehlende Bereitstellung 
der Artifakte, also dem Ergebnis der Actions.

### Repository konfigurieren

Damit bei einem Push automatisch eine Action ausgelöst wird,
erstellst du im Repository einen versteckten Ordner \ordner{.gitea}
mit einem Unterordner \ordner{workflows}. YAML-Dateien in diesem 
Ordner werden als Arbeitsanweisung verstanden. Leider ist die 
Syntax relativ gewöhnungsbedürftig, wird aber auf der 
Internetseite von \gitea ausführlich beschrieben.

[https://docs.gitea.com/usage/actions/quickstart?_highlight=qu](https://docs.gitea.com/usage/actions/quickstart?_highlight=qu)

**Beispiel: test.yml**  
```bash
name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

Committe nun diese Datei. Im Menü oben (Actions) kannst du im Detail 
beobachten, was passiert. Beim ersten Lauf muss ein Ubuntu-Image 
heruntergeladen werden -- die Basis des Containers -- und das dauert etwas!

Wenn das funktioniert hat, bist du einen Schritt weiter, aber noch lange nicht am Ziel!

### Quarto
Zum Erstellen des Buches wollen wir ein eigenes Quarto-Image verwenden. 
Die benötigten Dateien findest du im Material im Ordner *quarto*. 


Erstelle zunächst das Image:

```bash
docker build -t quarto-book .
```

Zum Testen startest du den Container

```bash
docker compose up 
```

und beendest ihn wieder mit \strg{c}. 

### Pipeline

Um mit diesem Image zu arbeiten müssen wir

* config.yml anpassen
* pipeline.yml im Ordner \ordner{.gitea/workflows} anlegen  
  (siehe unten)

#### config.yml

Hier geht es um die Label, die der Runner bearbeiten darf. 
Aktuell stehe verschiedene Ubuntus in der Liste

```bash
labels:
    - "ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest"
    - "ubuntu-24.04:docker://docker.gitea.com/runner-images:ubuntu-24.04"
    - "ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04"
    - "quarto:docker://quarto-book"
```

#### pipeline.yml

```bash

```