## Java 

### Idee 

Im Zusammenhang mit \git könnte ein Projekt für den Unterricht 
die Entwicklung einer Krypto-Software sein, bei der der Benutzer 
mit verschiedenene Methoden (Cäsar, Vigenere, ...) Klartext in 
verschlüsselten Text transformieren kann. Zentral wird eine 
kleine GUI bereitgestellt oder entwickelt, in die die Module 
der Projektgruppen eingebunden werden können.  

Nachfolgend nur kurz das Vorgehen für einen einfachen Cäsar mit 
GUI-Anbindung. Wem dies eine zu geringe Anforderung ist, kann auch gerne 
eine andere Technik umsetzen -- schlussendlich geht es eigentlich
um die Verwendung von Maven in diesem Zusammenhang.

Natürlich kann jede aktuelle IDE auf Knopfdruck auch Maven-Projekte 
generieren, wir wollen es hier aber *from scratch* durchführen,
um die Vorgänge hinter den Kulissen besser zu verstehen. Das ist u.a. 
deshalb nötig, weil für CI/CD Konfigurationsschritt nötig sind, die 
diesen hier ziemlich genau entsprechen.

### Erstellen des Projektes

Im Terminal wird bei bereits installiertem Maven eine 
korrekte Ordnerstruktur initialisiert.

```bash
mvn archetype:generate  -Dfilter=quickstart
```

Es müssen einige Parameter eingetellt werden:

```bash
Version: 1.5 (Taste 9)
groupID: de.alp.kurs
artifactID: krypto 
version: 1.0-SNAPSHOT
package: de.alp.kurs
Bestätigen: Y 
```

Das liefert folgende Struktur:

```bash
.
└── krypto
    ├── pom.xml
    └── src
        ├── main
        │   └── java
        │       └── de
        │           └── alp
        │               └── kurs
        │                   └── App.java
        └── test
            └── java
                └── de
                    └── alp
                        └── kurs
                            └── AppTest.java
```

Dieses Projekt kann bereits (fast) compiliert werden. 
Zuerst müssen wir allerdings noch einige Einträge in der 
\datei{pom.xml} angepasst werden:

* die lokal installierte Java-Version in die \datei{pom.xml} eintragen. 
  Default ist 17, ich verwende 21. 
* Konfiguration des *jar*-Plugin:

```bash
...
<plugin>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.4.2</version>
    <configuration>
        <archive>
            <manifest>
                <mainClass>de.alp.kurs.App</mainClass>
            </manifest>
        </archive>
    </configuration>
    </plugin>
...
```


Mit \cmd{mvn package} komplieren wir, führen einen Test aus und erstellen
das passende jar-Archiv.

```bash
java -jar target/krypto-1.0-SNAPSHOT.jar
```

