# Vorbemerkung{.unnumbered}
Git ist das aktuell wohl gängigste Versionskontrollsystem auf dem Markt.
Allerdings gibt es im Zusammenhang mit \git so viele verschiedene Aspekte
zu betrachten, dass eine stringente Einführung in das Thema relativ 
schwierig ist. In diesem Workshop kümmern wir uns schwerpunktmäßig um folgende 
Punkte:

* Installation (lokal und auf dem Server)
* Arbeiten als Single-Developer
* Arbeiten im Team (Grundlagen)
* Durchspielen von Anwendungsszenarien
* CI/CD und TDD auf ganz einfachem Niveau

Für den reinen Client-Aspekt ist die Verwendung von \git auf Windows problemlos. 
Sobald es aber um einen \git-Server geht, sind bessere Systeme wie Linux oder 
MacOS sinnvoller^[Ich habe bisher noch keinen Server im 
Internet getroffen, auf dem MacOS als Sytem verwendet wird. Das kann 
sich aber natürlich jederzeit ändern!]
Wir werden uns also mit beiden Welten (Windows und Linux) beschäftigen müssen.
Wer hier noch keine Erfahrung hat, wird viel profitieren!

 {{< include 0050_installation_1.qmd >}}
 {{< include 0070_installation_2.qmd >}}
 {{< include 0170_ersteSchritte.qmd >}}
 {{< include 0210_bash1.qmd >}}
 {{< include 0215_fehler.qmd >}}
 {{< include 0220_bash2.qmd >}}
 {{< include 0300_rebase.qmd >}}
 {{< include 0350_team.qmd >}}
 {{< include 0400_benutzer.qmd >}}
 {{< include 0450_basis.qmd >}}
 {{< include 0500_gitea.qmd >}}
 {{< include 0510_docker.qmd >}}
 {{< include 0520_giteadocker.qmd >}}
 {{< include 0530_gitea_actions.qmd >}}
 {{< include 0550_client.qmd >}}
 {{< include 0600_autograde.qmd >}}
 {{< include 0700_cicd.qmd >}}
 {{< include 0710_basis_ci.qmd >}}
 {{< include 0730_maven.qmd >}}
 {{< include 0750_tdd.qmd >}}
 {{< include 0810_java_anteil.qmd >}}
 {{< include 0850_cicdbuch.qmd >}}

ERLEDIGEN:  

Man kann alles speichern - aber sollte man?

Git Large File Storage (LFS)

https://www.youtube.com/watch?v=JOIL6gof2BA

11:36 Auflistung der Befehle


Unter der Haube

https://www.youtube.com/watch?v=RxHJdapz2p0&t=13s

