version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    restart: always
    hostname: '192.168.3.154'                    # im Netz hier url
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.3.154:443'  # hier unbedingt https + url
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - '22:22' # ssh für GitLab
      - '80:80' # http 
      - '443:443' # https
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - gitlab_net

networks:
  gitlab_net:
    external: true

