version: '3.8'
services:
  db:
    image: mariadb:8
    container_name: mariadb_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306" # Host-Port:Container-Port
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mariadb_network


  # phpMyAdmin Container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80" # Webinterface auf Port 8080 zugänglich

    networks:
      - mariadb_network
    depends_on:
      - db

volumes:
  mariadb_data:


# anzulegende Networks
networks:
  mariadb_network:
    driver: bridge
