# Verwende das offizielle MariaDB-Image
FROM mariadb:latest
# Optionale Konfiguration
# Beispiel: Anpassung der Konfiguration von MariaDB, wenn nötig
# COPY ./my.cnf /etc/mysql/my.cnf
# Um ein Initialisierungs-Skript hinzuzufügen
# (z.B. zum Erstellen einer Datenbank)
# COPY ./init.sql /docker-entrypoint-initdb.d/
# Setze Umgebungsvariablen (optional, falls nicht im docker-compose)
# ENV MYSQL_ROOT_PASSWORD=my-secret-pw
# ENV MYSQL_DATABASE=mydatabase
# ENV MYSQL_USER=myuser
# ENV MYSQL_PASSWORD=mypassword
