version: '3.8'
services:
  db:
    image: mariadb:8
    container_name: mariadb_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306" # Host-Port:Container-Port
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Optional: SQL-Datei zum Initialisieren
    networks:
      - mariadb_network


volumes:
  mariadb_data: # Persistente Volumes für Datenbankdaten

  # anzulegende Networks
networks:
  mariadb_network:
    driver: bridge
