---
title: "Proxmox verbiegen"
author: "Wolfgang Höfer"
format:
  pdf:
    documentclass: scrreprt
    lang: "de"
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{my_quarto_tools}
        \usepackage[top=2cm, bottom=2.5cm]{geometry}
        \usepackage{enumitem}
        \usepackage{changepage}
        \setlist[description]{style=nextline, leftmargin=2.5em}
        \newcommand{\cmd}[1]{\texttt{#1}\xspace}
jupyter: python3
---
# Proxmox mit NAT
## Situation

Im Schulungszentrum sollen die virtuellen Maschinen (VMs) 
auf dem Proxmox in einem isolierten Netzwerk laufen, 
damit der DHCP-Server keine zusätzlichen Adressen 
für sie bereitstellen muss. Das könnte Probleme mit
der örtlichen IT geben.

Um diese Konfiguration herzustellen, musst du auf 
dem frisch installierten Proxmox einige Schritte 
im Terminal ausgeführen. Um Kopieren und 
Einfügen möglich zu machen bauen wir eine ssh-Verbindung 
zum Proxmox auf. Zusätzlich öffnen wir aber auch noch 
eine Shell auf der Weboberfläche. Das ist nötig, weil  
uns nach dem Ändern des ssh-Ports von 22 auf 222 die 
Verbindung abreißen kann -- in der Webshell trifft uns 
das nicht (dort kann man aber schlecht kopieren und einfügen). 


## Anpassungen
### Installieren von Git
```bash
apt update
apt install git
```

## Scripte holen und starten
Die Scripte sind Bestandteil des Material im Ordner `proxmox`.
Clone das Repository

```bash
git clone https://github.com/gischupa/dillingen_material_git.git
cd dillingen_material_git/proxmox
bash change_config.sh
```

Wenn du über ssh gearbeitet hast, dürfte die Verbindung abgerissen sein.
Schließe das Terminalfenster und baue eine neue Verbindung über 
Port 222 auf:

```bash
ssh -p 222 root@<SERVER-IP>
```

### Images holen
Die Images befinden sich auf dem USB-Stick und müssen auf den 
Proxmox kopiert werden. Dafür gibt es keine GUI-Methode!

```bash
# Stick identifizieren
lsblk

# Wahrscheinlich siehst du sdb1
mount /dev/sdb1 /mnt
cp -r /mnt/* /var/lib/vz/template/iso/
umount /mnt
```

### Änderungen

Wenn du weitere Ports weiterleiten willst, oder noch andere
interne Netze anlegen willst, musst du genauer in die folgenden 
Dateien sehen:

```bash
/etc/network/interfaces
/usr/local/sbin/proxmox-vm-nat.sh
```

Nach Änderungen an den Firewallregeln muss ausgeführt weden:

```bash
systemctl deamon-reload
systemctl restart proxmox-vm-nat.service
```
## Schlusswort
Unser Docker-Host (die VM) muss bei der Installation unbedingt 
die IP 172.16.100.10 bekommen, denn das gesamte Firewalling 
ist auf diese IP ausgerichtet. Anfragen an den Proxmox, die 
über die Ports 22, 4000 und 8080 erfolgen, werden direkt 
an die VM auf diesen Ports weitergeleitet.


